In [2]:
import pandas as pd
import numpy as np

In [4]:
input = [2, 3, 4, 5]
weights = [0.1, 0.2, 0.3, 0.4]
bias = 2

output = (input[0]*weights[0] +
          input[1]*weights[1] +
          input[2]*weights[2] +
          input[3]*weights[3] +
          bias)

output = max(0,output)
print(output)

6.0


In [7]:
input = [2, 3, 4, 5]
weights1 = [0.1, 0.2, 0.3, 0.4]
weights2 = [0.2, 0.3, 0.4,0.5]
weights3 = [0.3, 0.4, 0.5, 0.6]

bias1 = -5
bias2 = 6
bias3 = 2

output = [
    input[0]*weights1[0] + input[1]*weights1[1] + input[2]*weights1[2] + input[3]*weights1[3] + bias1,
    input[0]*weights2[0] + input[1]*weights2[1] + input[2]*weights2[2] + input[3]*weights2[3] + bias2,
    input[0]*weights3[0] + input[1]*weights3[1] + input[2]*weights3[2] + input[3]*weights3[3] + bias3
]
print(output)

[-1.0, 11.4, 8.8]


In [8]:
input = [2, 3, 4, 5]
weights= [[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6]]
bias = [ -5, 6, 2]
matrix_output = np.dot(weights, input) + bias
print(matrix_output)

[-1.  11.4  8.8]


In [9]:
inputs = [2,3,4,5]
weights = [[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6]]
bias = [-5, 6, 2]

layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[-1.0, 11.4, 8.8]


In [12]:
input = [4,5,6,7]
weights = [0.1, 0.2, 0.3, 0.4]
bias = 3

output = np.dot(weights, input) + bias
print( max(0, output))

9.0


In [19]:
input = np.array([
    [0.3, 0.5, 0.7, 0.9],
    [0.2, 0.4, 0.6, 0.8],
    [0.1, 0.3, 0.5, 0.7]
])

weights = np.array([[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6]])

bias = np.array([-5, 6, 2])
output = np.dot(weights, input.T) + bias
print(output)

[[-4.3   6.6   2.5 ]
 [-4.06  6.8   2.66]
 [-3.82  7.    2.82]]


In [ ]:
import numpy as np

# Input data: 3 students/samples, 4 features each
inputs = np.array([
    [0.3, 0.5, 0.7, 0.9],
    [0.2, 0.4, 0.6, 0.8],
    [0.1, 0.3, 0.5, 0.7]
])

# Weights: 3 neurons, each neuron has 4 weights
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.2, 0.3, 0.4, 0.5],
    [0.3, 0.4, 0.5, 0.6]
])

# Bias: one bias for each neuron
bias = np.array([-5, 6, 2])

# Forward pass
net_output = np.dot(inputs, weights.T) + bias

# Step activation for PASS / FAIL
# >= 0 means PASS, < 0 means FAIL
results = np.where(net_output >= 0, "PASS", "FAIL")

print("Net output:")
print(net_output)

print("\nClassification:")
print(results)

Net output:
[[-4.3   6.94  3.18]
 [-4.4   6.8   3.  ]
 [-4.5   6.66  2.82]]

Classification:
[['FAIL' 'PASS' 'PASS']
 ['FAIL' 'PASS' 'PASS']
 ['FAIL' 'PASS' 'PASS']]


In [2]:
import numpy as np
input =([1.3, 2, 3.4, 4.5])

weights = ([[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6], [0.4, 0.5, 0.6, 0.7]])

bias = ([-5, 6, 2])

weights2 = ([[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6], [0.4, 0.5, 0.6, 0.7]])
bias2 = ([-5, 6, 2])

weights3 = ([[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6], [0.4, 0.5, 0.6, 0.7]])
bias3 = ([-5, 6, 2])

weights4 = ([[0.1, 0.2, 0.3, 0.4], [0.2, 0.3, 0.4,0.5], [0.3, 0.4, 0.5, 0.6], [0.4, 0.5, 0.6, 0.7]])
bias4 = ([-5, 6, 2])

output1 = np.dot(input, np.array(weights).T) + bias
output1 = np.maximum(0, output1)  # ReLU activation
print("Output for the first layer:", output1, sep=',')

output2 = np.dot(output1, np.array(weights2).T) + bias2
output2 = np.maximum(0, output2)  # ReLU activation
print("Output for the second layer:", output2, sep=',')

output3 = np.dot(output2, np.array(weights3).T) + bias3
output3 = np.maximum(0, output3)  # ReLU activation
print("Output for the third layer:", output3, sep=',')

output4 = np.dot(output3, np.array(weights4).T) + bias4
output4 = np.maximum(0, output4)  # ReLU activation
print("Output for the fourth layer:", output4, sep=',')



ValueError: operands could not be broadcast together with shapes (4,) (3,) 